### ISSUE TITLE
Portfolio Review- Cgleach

### ISSUE THREAD

**Issue by cgleach** [w201rdada/portfolio-kckenneth#1]
Overall I find the idea fascinating!  The prospect of using sentient machines to help supplement the human experience is something I personally don't think gets discussed enough, so I'm very excited to see where you take this.  

Things to Keep:

1) I enjoyed the way you often posed questions to the reader, and really made them feel as if they were a part of the discussion.  I think this is a powerful tool and shouldn't go away (however see below)

Things to Consider:  

1) I really like your idea, but it doesn't become clear what you're proposing until the end of the portfolio.  It would help the reader have context in the middle section if you outline the idea from the start.

2) While some questions throughout stregthen the peice, there are times when it feels like you are asking the reader to do too much of the work through answering the questions you pose.  I might consider cutting back--but not eliminating--this technique.

Items to Add: 

1) I agree with your point that there are use cases for emotional/sentient machines, and you suggest one (nursing homes), but I would have loved to see some data around this (e.g. how many individuals currently live in nursing homes without extended family)

2) While not essential to your peice, I would have been curious to know if there are any potential philosophical questions associated with this development (e.g. what happens when people begin falling in love with robots?)

**Comment by kckenneth** [comment]
Thanks very much, Clay. Appreciate your input. Definitely an interesting area to explore. I'd like to do research on this particular domain. But with a limited time I have now, it's very hard to ink my idea in a very polished way. Considering a recent development at the Boston Dynamics, robots walking, flipping, imagine if we add another algorithm to the same memory chip to draw Van Gogh, to play football, to predict stock price, to speak different languages, what I found missing is the core algorithm to control all those discrete algorithms to suit the robots interest the best (kind of 'selfish gene'). This will be a robot war to steal and gain the algorithm to their survival in the future (kind of fictional thinking). Hacking their algorithm to stop working or jamming is basically killing them. 

Definitely my line of thinking as well. If we fall in love with robots, I think we're not gonna repopulate the world where machine will rule. haha

A few movies stood out: 
1. Her
2. Human (TV series)
3. Ex Machina

Thanks for this very thoughtful comment. 

https://w201rdada.github.io/portfolio-kckenneth/
