### ISSUE TITLE
Review-Bigidea#1

### ISSUE THREAD

**Issue by rahul-kulkarni** [w201rdada/portfolio-kckenneth#2]
Its an interesting topic, reminds me of the movie - wall-e ;->
Human sentiment is already being gleaned today from what we like, buy, eat and where we go, whom we hang out with etc. Now if you build a snapshot of that and play out this sentiment in a robot over a time  you could build a machine who behaves like you.  But this again is at a layer way above - essentially how a person acts out externally in a world can be mirrored. But when you talk about conciseness and sentiments of say anger or joy it gets into difficult terrain. You could teach a robot to tell a joke if it can detect crying but I think human emotions are way to layered and complex which may be hard to model.

But yes - It is a Big Idea for sure!

**Comment by kckenneth** [comment]
Thanks very much Rahul. Definitely an interesting point you brought up. Humans have many emotions and they have many layered, some even are built upon a century old traditions, cultures and norms. We cannot simply develop an algorithm to appreciate those cultural value. A fine line between self-esteem and arrogance, or self-effacing and indifference, all those are very hard to predict. Natural Language processing is still at an infant stage as of now, it would be very hard to write a program that will perceive a human emotion. 

Wall E is one of my favorite ones. A few other: Her, Ex-Machina. 

We are definitely seeing a big change in machine learning and how it is transforming all the things we are seeing these days for sure. 

Thanks again for your perspective. 

https://w201rdada.github.io/portfolio-kckenneth/
